### PR TITLE
Update and fix tutorials

### PR DESCRIPTION
**Pull request by keyleu**
Description:

- Update everything to coreum v3.
- Fix all go tutorials to work with v3.
- Update cosmjs to newest version for TS tutorials.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/tutorials/9)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/tutorials/9)* status: all files reviewed, 3 unresolved discussions (waiting on @Islandersfan2016, @Jovonni, @keyleu, and @wanesurf)

___
*[`go/create-fungible-token/main.go` line 60 at r1](https://reviewable.io/reviews/CoreumFoundation/tutorials/9#-NjCmk7f3h7Aq7oLT7fS:-NjCmk7f3h7Aq7oLT7fT:b-5e0vzf) ([raw file](https://github.com/CoreumFoundation/tutorials/blob/70db3974a693a6a4fadccb7effe49594be20c64f/go/create-fungible-token/main.go#L60)):*
> ```Go
> 		WithChainID(string(chainID)).
> 		WithGRPCClient(grpcClient).
> 		WithKeyring(coreumkeyring.NewConcurrentSafeKeyring(keyring.NewInMemory(encodingConfig.Codec))).
> ```

`coreumkeyring.NewConcurrentSafeKeyring` - we introduced it for our integration-tests mostly
I'm not sure we should suggest it 

@wojtek-coreum @dzmitryhil @miladz68 WDYT ?
___
*[`go/create-fungible-token/main.go` line 82 at r1](https://reviewable.io/reviews/CoreumFoundation/tutorials/9#-NjCn6Nh4rAih7iEW5ml:-NjCn6Nh4rAih7iEW5mm:b-lv2idr) ([raw file](https://github.com/CoreumFoundation/tutorials/blob/70db3974a693a6a4fadccb7effe49594be20c64f/go/create-fungible-token/main.go#L82)):*
> ```Go
> 
> 	// Broadcast transaction issuing new fungible token
> 	senderAddress, _ := senderInfo.GetAddress()
> ```

what is the second return arg here ?
If it is err I'm not sure we should ignore it
___
*[`go/create-non-fungible-token/main.go` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/tutorials/9#-NjCnQsC1GyVPCQsMGAk:-NjCnQsC1GyVPCQsMGAl:b-dvgxmc) ([raw file](https://github.com/CoreumFoundation/tutorials/blob/70db3974a693a6a4fadccb7effe49594be20c64f/go/create-non-fungible-token/main.go#L18)):*
> ```Go
> 
> 	"github.com/CoreumFoundation/coreum/v3/pkg/client"
> 	coreumconfig "github.com/CoreumFoundation/coreum/v3/pkg/config"
> ```

same comments as in prev file
But lets decided there first

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/tutorials/9)* status: 9 of 12 files reviewed, 3 unresolved discussions (waiting on @Islandersfan2016, @Jovonni, @wanesurf, and @ysv)

___
*[`go/create-fungible-token/main.go` line 82 at r1](https://reviewable.io/reviews/CoreumFoundation/tutorials/9#-NjCn6Nh4rAih7iEW5ml:-NjCuBLpDw23YNjf8v6o:b-noatsm) ([raw file](https://github.com/CoreumFoundation/tutorials/blob/70db3974a693a6a4fadccb7effe49594be20c64f/go/create-fungible-token/main.go#L82)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what is the second return arg here ?
If it is err I'm not sure we should ignore it
</blockquote></details>

Yes, it's err. I fixed to panic with error like in the rest of the places.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/tutorials/9)* status: 9 of 12 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @Islandersfan2016, @Jovonni, @miladz68, @wanesurf, @wojtek-coreum, and @ysv)

___
*[`go/create-fungible-token/main.go` line 60 at r1](https://reviewable.io/reviews/CoreumFoundation/tutorials/9#-NjCmk7f3h7Aq7oLT7fS:-NjD3I9pE2Zhztdvjlcs:b-wpkdfl) ([raw file](https://github.com/CoreumFoundation/tutorials/blob/70db3974a693a6a4fadccb7effe49594be20c64f/go/create-fungible-token/main.go#L60)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`coreumkeyring.NewConcurrentSafeKeyring` - we introduced it for our integration-tests mostly
I'm not sure we should suggest it 

@wojtek-coreum @dzmitryhil @miladz68 WDYT ?
</blockquote></details>

like discussed. I removed it.
___
*[`go/create-non-fungible-token/main.go` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/tutorials/9#-NjCnQsC1GyVPCQsMGAk:-NjD3Kyv5XO5_9-EikN9:b9w3796) ([raw file](https://github.com/CoreumFoundation/tutorials/blob/70db3974a693a6a4fadccb7effe49594be20c64f/go/create-non-fungible-token/main.go#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

same comments as in prev file
But lets decided there first
</blockquote></details>

Like above, removed it everywhere.

**Comment by wanesurf** [comment]
- Create new FT token (Issue) ✅ : 
 https://explorer.testnet-1.coreum.dev/coreum/transactions/6C10FE43C431F615838ADA5A57DA41033753EAD0D43A21E7404546B90BF7DD63
 - Send FT token  ✅: 
 https://explorer.testnet-1.coreum.dev/coreum/transactions/A57C2B65FA55F8570D38CE46BFBE08A29994C4EB1C6B4A4A4570D9D94B1A7D5B
 - Query Balance FT ✅: 
 
Screenshot 2023-11-14 at 4 26 29 PM

- Freezing ✅ : 
-https://explorer.testnet-1.coreum.dev/coreum/transactions/EB245DC08553DBE31A97F1C03F49E86A08CC9E833D03784BA179175E35B0AB45

**Comment by wanesurf** [comment]
**Test create-new-nft :** 

-  Broadcast transaction issuing new nft class  ✅: 
https://explorer.testnet-1.coreum.dev/coreum/transactions/01AA744142515555338B74C38685B1E2B881A2A6AFC3358957C9AEA841C165CC
-  Broadcast transaction minting new nft (MINT)  ✅ : 
https://explorer.testnet-1.coreum.dev/coreum/transactions/027B6DACF49090647B739437811A64E3AFD41CF64422D9FC585E51C9DDE6CF90
-  Query the owner of the NFT   ✅ :
Screenshot 2023-11-14 at 5 32 17 PM
- Send the NFT to someone ✅  : 
https://explorer.testnet-1.coreum.dev/coreum/transactions/ECB2FEEE064CF7B4168024E19B8A5637EC2B18ABA4FDF848EB50F0114693E150
- Query the owner of the NFT again ✅: 
Screenshot 2023-11-14 at 5 36 25 PM
-  Freeze balance portion of the recipient's balance ✅: 
https://explorer.testnet-1.coreum.dev/coreum/transactions/C1BD4C24149E5613E14E9E337D71331920C5C201AF191B0B33E41416DB175130

**Pull request merged**
